services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=blogdb
      - DB_PASSWORD=password
      - DB_PORT=5432
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  test:
    build: .
    command: npm test
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=blogdb
      - DB_PASSWORD=password
      - DB_PORT=5432

volumes:
  postgres_data: